{{- if .Values.additionalTaskManagers.large.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-application-cluster-taskmanager-large
  namespace: default
spec:
  selector:
    matchLabels:
      app: flink
      role: taskmanager
  template:
    metadata:
      labels:
        app: flink
        role: taskmanager
        release: monitoring
    spec:
      serviceAccount: flink
      containers:
        - name: taskmanager
          image: flink:1.20
          command: ["/docker-entrypoint.sh", "taskmanager"]
          resources:
            requests:
              memory: "12Gi"
              cpu: "6"
            limits:
              memory: "12Gi"
              cpu: "6"
          env:
            - name: FLINK_CONF_DIR
              value: /opt/flink/conf
            - name: FLINK_PROPERTIES
              value: |
                taskmanager.numberOfTaskSlots: 16
                taskmanager.memory.process.size: 12gb
          ports:
            - containerPort: 9249
              name: metrics
              protocol: TCP
          volumeMounts:
            - name: flink-config-volume
              mountPath: /opt/flink/conf
            - name: flink-job-dir
              mountPath: /flink-jobs/
      volumes:
        - name: flink-config-volume
          configMap:
            name: flink-config-flink-application-cluster
        - name: flink-job-dir
          hostPath:
            path: /tmp/flink/jobs
            type: DirectoryOrCreate
{{- end }}
