# Default values for flink.
additionalTaskManagers:
  medium:
    enabled: false
  large:
    enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1000
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

