apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: demo-kafka
  namespace: default
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      kafka-metrics: 'true'
  podMetricsEndpoints:
    - path: /metrics
      interval: 30s
      port: tcp-prometheus
