apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flink-cluster-metrics
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      release: monitoring
  podMetricsEndpoints:
    - port: metrics
      interval: 1s
