{
 "title": "UpStream Metrics",
 "description": "The metrics used by the UpStream scaler to scale the number of task managers of the flink cluster.",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Average Busy Time ms/s",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(flink_taskmanager_job_task_busyTimeMsPerSecond)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Idle Time ms/s",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(flink_taskmanager_job_task_idleTimeMsPerSecond)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Input Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_inputQueueLength)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backpressure Time ms/s",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(flink_taskmanager_job_task_backPressuredTimeMsPerSecond)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}