#!/usr/bin/env bash
set -euo pipefail

kubectl port-forward service/flink-application-cluster-rest 8081:8081 &
kubectl port-forward service/prometheus-operated 9090:9090 &

echo "Press CTRL-C to stop port forwarding and exit the script"
wait
